---
- hosts: all
  vars_files:
    - ../vars/main.yml

  tasks:

    - name: Create a test script 
      become: true
      file:
        path: "{{checkbox_folder}}/server-side/site/test.js"
        state: touch
        mode: 0777
      register: test_file

    - name: Create process.json  
      become: true
      file:
        path: "{{checkbox_folder}}/server-side/site/process.json"
        state: touch
        mode: 0777  

    - name: Copy contents to process.json
      become: true
      blockinfile:
         path: "{{checkbox_folder}}/server-side/site/process.json"
         marker: ''
         block: |    
           {
            "apps" : [{
              "name"    :"checkbox-server",
              "script"  :"server.js",
              "args"    :"start"

            }
            ]
           }

    - name: Copy test content into file
      become: true
      copy:
        src: "/ansible-server/templates/test.js"
        dest: "{{checkbox_folder}}/server-side/site"
        force: yes

    - name: Run the test from the correct directory
      command: npm test
      args:
        chdir: ~/checkbox/server-side/site  

           

