---
- hosts: all
  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Check if a test directory exists in checkbox repo
      stat:
        path: "{{checkbox_folder}}/server-side/test"
      register: test_directory  

    - name: Create test directory in checkbox repository
      become: true
      file:
        path: "{{checkbox_folder}}/server-side/test"
        state: directory
        mode: 0777
      when: test_directory.stat.exists == False

    - name: Create a test script 
      become: true
      file:
        path: "{{checkbox_folder}}/server-side/test/test.js"
        state: touch
        mode: 0777
      register: test_file
      
    # - name: Copy test content into file
    #   blockinfile:
    #      path: "{{checkbox_folder}}/server-side/test/test.js"
    #      marker: '"//: Ansible"'
    #      block: |
           

