---
- hosts: all
  vars_files:
    - ../variables.yml

  tasks:
  - name: Install esprima npm package
    npm:
      name: "esprima@4.0"
      path: "{{checkbox_folder}}"
      state: present
    become: true


  - name: Remove build.txt file if it exists in checkbox folder
    become: true
    file:
      state: absent
      path: "{{checkbox_folder}}/build.txt"

  - name: Copy analysis file to checkbox folder
    become: true
    copy:
      src: "/ansible-server/templates/checkboxanalysis.js"
      dest: "{{checkbox_folder}}"
      force: yes  
    
  - name: Run checkbox analysis for the first three tasks
    become: true
    shell: node checkboxanalysis.js
    args:
     chdir: "{{checkbox_folder}}" 
    register: shell_result

  - name: Check if build.txt exists in checkbox folder
    become: true
    stat:
      path: "{{checkbox_folder}}/build.txt"
    register: checkbox_build   

  - name: Copy build.txt to checkbox job folder if it exists
    become: true
    copy:
      src: "{{checkbox_folder}}/build.txt"
      dest: "/var/lib/jenkins/workspace"
      force: yes  
      remote_src: yes
    when: checkbox_build.stat.exists == true   

  - name: Update jenkins job
    become: true
    command: "jenkins-jobs update jobs"  
    args:
      chdir: /home/vagrant

#AST tree diff 
  # - name: Create a directory for the Gradle installation
  #   become: true
  #   file:
  #     path: /opt/gradle
  #     state: directory   
  #     mode: 0777

  # - name: Download Gradle
  #   become: true
  #   get_url:
  #     url: https://services.gradle.org/distributions/gradle-3.4.1-bin.zip
  #     dest: /opt/gradle
  #     mode: 0777
    
  # - name: Check for downloaded gradle file
  #   stat:
  #     path: /opt/gradle/gradle-3.4.1-bin.zip
  #   register: gradle_file       

  # - name: Install Gradle
  #   become: true
  #   command: unzip /opt/gradle/gradle-3.4.1-bin.zip
  #   args:
  #     chdir: /opt/gradle
  #   when: gradle_file.stat.exists == true

  # - name: Check for installed gradle file
  #   stat:
  #     path: /opt/gradle/gradle-3.4.1  
  #   register: gradle_file_installed

  # # SET ENVIRONMENT VARIABLE export PATH=$PATH:/opt/gradle/gradle-3.4.1/bin

  # - name: Check for cloned Gumtree repo
  #   stat:
  #     path: "{{gumtree_folder}}"
  #   register: gumtree_repo   

  # - name: Clone GumTree as AST difference tool
  #   become: true
  #   git:
  #     repo: https://github.com/GumTreeDiff/gumtree.git
  #     dest: "{{gumtree_folder}}"
  #   when: gumtree_repo.stat.isdir is not defined
     

  # - name: Build GumTree
  #   become: true
  #   command: ./gradlew build -x test
  #   args:
  #     chdir: "{{gumtree_folder}}" 
 
  # - name: Check for zip folder of GumTree
  #   become: true
  #   stat: path="{{gumtree_folder}}/dist/build/distributions/gumtree-2.1.3-SNAPSHOT.zip"  
  #   register: build_gumtree

  # - name: Unzip GumTree
  #   become: true
  #   command: "unzip {{gumtree_folder}}/dist/build/distributions/gumtree-2.1.3-SNAPSHOT.zip"
  #   args:
  #     chdir: "{{gumtree_folder}}/dist/build/distributions"
  #   when: build_gumtree.stat.exists == True  

  # - name: Check for gumtree folder in checkbox
  #   become: true
  #   stat: path="{{checkbox_folder}}/gumtree-2.1.3-SNAPSHOT"
  #   register: gumtree_file

  # - name: Move Gumtree zip folder to checkbox
  #   become: true
  #   command: "mv {{gumtree_folder}}/dist/build/distributions/gumtree-2.1.3-SNAPSHOT {{checkbox_folder}}"   
  #   when: gumtree_file.stat.exists == False    
