---
- hosts: all
  vars_files:
    - ../variables.yml

  tasks:
  - name: Remove Fuzzer directory if it exists
    become: true
    file:
      state: absent
      path: "{{fuzzer_folder}}"

  - name: Create fuzzer directory
    become: true
    file:
      path: "{{fuzzer_folder}}"
      state: directory 
  
  - name: Copy files into fuzzer directory
    become: true
    template:
      src: "{{item}}"
      dest: "{{fuzzer_folder}}"
      force: yes
    with_items:
      - /ansible-server/templates/package.json
      - /ansible-server/templates/fuzzer.js
      - /ansible-server/templates/initiateFuzzer.js

  - name: Install shelljs npm package
    npm:
      name: "{{item}}"
      path: "{{ fuzzer_folder}}"
      state: present
    become: true
    with_items: 
      - shelljs
      - path

  - name: Start the Commit Fuzzer
    become: true
    shell: 'node initiateFuzzer.js; sleep 15'
    args:
      chdir: "{{fuzzer_folder}}"
    with_sequence: "count=3"