---
- hosts: all
  vars_files:
    - ../variables.yml

  tasks:
  - name: Create fuzzer directory
    file:
      path: "{{fuzzer_folder}}"
      state: directory 
  
  - name: Copy files into fuzzer directory
    template:
      src: "{{ item }}"
      dest: "{{fuzzer_folder}}"
      force: yes
    with_items:
      - /home/vagrant/share/JenkinsTestAnalysis/templates/fuzzer.js
      - /home/vagrant/share/JenkinsTestAnalysis/templates/initiateFuzzer.js

  - name: Start the Commit Fuzzer
    become: yes
    shell: 'node initiateFuzzer.js; sleep 15'
    args:
      chdir: "{{fuzzer_folder}}"
    with_sequence: "count=100"