---
- hosts: all
  vars_files:
    - ../vars/main.yml

  tasks:
  - name: Install request module for test 
    command: sudo npm install request --save
    args:
      chdir: ~/checkbox/server-side/site/node_modules
   
  - name: Install got module for test
    command: sudo npm install got --save
    args:
      chdir: ~/checkbox/server-side/site/node_modules
    
  - name: Install shelljs for test
    command: sudo npm install shelljs
    args:
      chdir: ~/checkbox/server-side/site/node_modules    


  - name: Install chai module for test
    command: sudo npm install chai --save
    args:
      chdir: ~/checkbox/server-side/site/node_modules
    
      
  - name: Install child process for test
    command: sudo npm install child_process
    args:
      chdir: ~/checkbox/server-side/site/node_modules

  - name: Install mocha on server
    become: true
    npm:
      name: mocha
      global: yes          

  - name: Install pm2 on server
    become: true
    npm:
      name: pm2
      global: yes


