---
- hosts: all
  become: true
  vars_prompt:
    - name: "mysql_root_password"
      prompt: Please enter password for MySQL
      private: yes
  tasks:
    - name: Setting MySQL root password before installing
      become: true
      debconf:
        name: mysql-server
        question: mysql-server/root_password
        value: '{{mysql_root_password}}'
        vtype: password

    - name: Confirm MySQL password before installing
      become: true
      debconf:
        name: mysql-server
        question: mysql-server/root_password_again
        value: '{{mysql_root_password}}'
        vtype: password

    - name: Installing MySQL Server
      become: true
      apt: 
        name: ['python3-mysqldb', 'mysql-server', 'python-pymysql'] 
        update_cache: yes 
        cache_valid_time: 3600 
        state: present
    
    - name: Updating password
      mysql_user: 
        name: root
        password: "{{mysql_root_password}}"
        state: present
        check_implicit_admin: yes
        login_user: root
        login_password: "{{mysql_root_password}}"

    - name: Creating vagrant user 'vagrant'@'192.168.33.200'
      mysql_user:
        name: vagrant 
        host: "{{item}}"
        sql_log_bin: yes
        password: "{{mysql_root_password}}"
        priv: '*.*:ALL,GRANT'
        state: present
        login_user: root
        login_password: "{{mysql_root_password}}"
      with_items:
        - 192.168.33.200
        - 'localhost'
        - '{{ansible_hostname}}'
        - 127.0.0.1