---
- hosts: all
  vars_files:
    - ../variables.yml

  tasks:
  - name: Remove Test directory if it exists
    become: true
    file:
      state: absent
      path: "{{test_analysis_folder}}"

  - name: Create test directory
    become: true
    file:
      path: "{{test_analysis_folder}}"
      state: directory 
  
  - name: Copy files into test directory
    become: true
    template:
      src: "/ansible-server/templates/testprioritization.js"
      dest: "{{test_analysis_folder}}"
      force: yes

  - name: Install shelljs npm package
    npm:
      name: "{{item}}"
      path: "{{test_analysis_folder}}"
      state: present
    become: true
    with_items: 
      - path
      - jenkins-api
      - xml2js

  # - name: Start the Test Prioritization script
  #   become: true
  #   shell: 'node testprioritization.js; sleep 15'
  #   args:
  #     chdir: "{{test_analysis_folder}}"