#!/bin/sh
echo "Current location: $GIT_DIR"
GIT_WORK_TREE=/home/{{ ansible_user }}/deploy/checkbox-www git checkout -f
echo "Pushed to production!"
# EC2 instance js file
sudo node /home/{{ ansible_user }}/deploy/checkbox.git/aws-checkbox.js
sudo chown ubuntu /home/{{ ansible_user }}/checkbox/Checkbox.pem 
# run the checkbox task
# cd ../production-jenkins
# curl http://localhost:8090/job/job_name/build?delay=0sec
