---
  - name: install jre8
    apt:
     name: openjdk-8-jre
     state: present
     update_cache: yes
    become: true

  - name: add jenkins repo key
    apt_key:
     url: https://pkg.jenkins.io/debian/jenkins.io.key
     state: present
    become: true

  - name: add jenkins repo list file into sources.list.d
    apt_repository:
     repo: deb http://pkg.jenkins.io/debian-stable binary/
     state: present
    become: true

  - name: install jenkins
    apt:
     name: jenkins
     state: present
     update_cache: yes
    become: true

  - name: Start Jenkins service and enable on boot
    service:
      name: jenkins
      state: started
      enabled: yes


# configuring
   
  - name: reading admin password
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: adminpwd
    become_user: jenkins
    become: true
   
  
  - name: Add admin and unlock Jenkins automatically
    jenkins_script: 
     script: "{{ lookup('file' , 'templates/groovy_add_user.groovy') }}"
     user: admin
     password: "{{ adminpwd.stdout }}"

  - name: sign into jenkins and complete setup
    jenkins_script:
     script: "{{ lookup('file' , 'templates/groovy_setup_user.groovy') }}"
     user: admin
     password: "{{ adminpwd.stdout }}"

  - name: disable security for installation
    become: true
    lineinfile: 
      dest: /var/lib/jenkins/config.xml
      regexp: '<useSecurity>true</useSecurity>'
      line: '  <useSecurity>false</useSecurity>'


   #- name: give enough time for jenkins to reload
    # uri:
     #  url: http://192.168.33.200:8080
      # url_username: adminpwd
       #url_password: "{{ adminpwd.stdout }}"
       #status_code: 200
       #timeout: 5
     #register: jenk_status
     #retries: 20
     #delay: 5
     #until: "'stat' in jenk_status and jenk_status['stat'] == 200"

  - name: plugins installation
    become: true
    become_user: jenkins
    jenkins_plugin:
      name: "{{ item }}"
      state: latest
      url_username: admin
      url_password: "{{ adminpwd.stdout }}"
      url: http://192.168.33.200:8080
      validate_certs: no
    with_items: "{{ plugins }}"

  - name: Restart jenkins
    become: true
    command: systemctl restart jenkins 

