---
# tasks file for jenkins
# - name: Installing and Configuring Jenkins
#   include: jenkins.yml

- name: Setting up checkbox.io application
  include: checkbox.yml

# - name: Setting up iTrust application
#   include: itrust.yml

- name: Installing mocha and pm2 for testing node applications
  include: mocha.yml

